name: fpd-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas=2.2.0
  - numpy=1.26.4
  - scikit-learn=1.4.0
  - joblib=1.3.2
  - pip:
    - fastapi==0.109.2
    - uvicorn==0.27.1
    - supabase==2.27.3
    - httpx==0.26.0
    - aiohttp==3.9.3
    - python-jose==3.3.0
    - python-dotenv==1.0.1
